### ISSUE TITLE
Translate `Communautés` wiki page to english `Communities` wiki page.

### ISSUE THREAD

**Issue by MidasTurtle** [MidasTurtle/slidn#2]
- Add a link from `Communautés` wiki page to `Communities` wiki page with an american flag.
- Add a link from `Communities` wiki page to `Communautés` wiki page with a french flag.

**Comment by MidasTurtle** [comment]
Link :
https://github.com/MidasTurtle/slidn/wiki/Communaut%C3%A9s

**Comment by Nadeus** [comment]
Done
